# Generated by Django 5.2.8 on 2026-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('gym_admin', 'Gym Admin'), ('coach', 'Coach'), ('athlete', 'Athlete'), ('nutritionist', 'Nutricionista'), ('receptionist', 'Atención al Cliente')], default='athlete', max_length=20),
        ),
    ]
