# Generated by Django 5.2.8 on 2026-05-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_dni_user_phone'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gyms', '0004_gym_max_athletes_gym_max_coaches_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['gym', 'role'], name='accounts_us_gym_id_7e86a6_idx'),
        ),
    ]
