# Generated by Django 5.2.8 on 2026-05-23 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_accounts_us_gym_id_7e86a6_idx'),
        ('gyms', '0005_gymmembershipplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.AddField(
            model_name='user',
            name='membership_plan',
            field=models.ForeignKey(blank=True, help_text='Plan de membresía del atleta en este gimnasio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='gyms.gymmembershipplan'),
        ),
    ]
