# Generated by Django 5.2.8 on 2026-06-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership_plan',
        ),
    ]
