# Generated by Django 5.2.8 on 2026-06-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_membership_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='user',
            name='max_clients',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
