# Generated by Django 5.2.8 on 2026-06-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Pérdida de peso'), ('muscle_gain', 'Ganancia muscular'), ('endurance', 'Resistencia'), ('flexibility', 'Flexibilidad'), ('sport_perf', 'Rendimiento deportivo'), ('general_fitness', 'Fitness general')], max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_notes',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
