# Generated by Django 5.2.8 on 2026-06-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_fitness_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
