# Generated by Django 5.2.8 on 2026-06-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_nivel_from_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='puntos',
        ),
    ]
