# Generated by Django 5.2.8 on 2025-11-16 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0002_gym_contact_email_gym_website_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionMeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('meal_time', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Almuerzo'), ('dinner', 'Cena'), ('snack', 'Snack')], default='breakfast', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NutritionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.CharField(max_length=255)),
                ('portion', models.CharField(max_length=120)),
                ('macros', models.JSONField(blank=True, default=dict)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.nutritionmeal')),
            ],
            options={
                'ordering': ['meal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('calories_per_day', models.PositiveIntegerField(default=2000)),
                ('macros', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='gyms.gym')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='nutritionmeal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.nutritionplan'),
        ),
        migrations.CreateModel(
            name='UserNutritionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado')], default='active', max_length=20)),
                ('compliance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_nutrition_plans', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='nutrition.nutritionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('user', 'plan', 'status')},
            },
        ),
    ]
