# Generated by Django 5.2.8 on 2025-11-18 22:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_remove_pollito_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionplan',
            name='macros',
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='carbs_g',
            field=models.PositiveIntegerField(default=200, help_text='Gramos de carbohidratos por día'),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=7, help_text='Duración del plan en días (ej: 7, 14, 30)'),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='fats_g',
            field=models.PositiveIntegerField(default=65, help_text='Gramos de grasas por día'),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='points_reward',
            field=models.PositiveIntegerField(default=0, help_text='Puntos al completar el plan'),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='protein_g',
            field=models.PositiveIntegerField(default=150, help_text='Gramos de proteína por día'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='calories_per_day',
            field=models.PositiveIntegerField(default=2000, help_text='Calorías objetivo por día'),
        ),
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveIntegerField(help_text='Día del plan (1-7 para semanal, null para opciones flexibles)')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Almuerzo'), ('dinner', 'Cena'), ('snack', 'Snack')], max_length=20)),
                ('name', models.CharField(help_text='Nombre de la comida (ej: Avena con Frutas)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción o instrucciones')),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein_g', models.PositiveIntegerField(default=0)),
                ('carbs_g', models.PositiveIntegerField(default=0)),
                ('fats_g', models.PositiveIntegerField(default=0)),
                ('ingredients', models.TextField(blank=True, help_text='Lista de ingredientes separados por línea')),
                ('instructions', models.TextField(blank=True, help_text='Instrucciones de preparación')),
                ('order', models.PositiveIntegerField(default=1, help_text='Orden de visualización')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_templates', to='nutrition.nutritionplan')),
            ],
            options={
                'ordering': ['plan', 'day_number', 'order', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='UserMealLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Fecha en que se consumió la comida')),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Notas del usuario')),
                ('meal_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to='nutrition.mealtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'meal_template__order'],
            },
        ),
        migrations.AddIndex(
            model_name='mealtemplate',
            index=models.Index(fields=['plan', 'day_number', 'meal_type'], name='nutrition_m_plan_id_518d25_idx'),
        ),
        migrations.AddIndex(
            model_name='usermeallog',
            index=models.Index(fields=['user', 'date'], name='nutrition_u_user_id_e8b4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='usermeallog',
            index=models.Index(fields=['user', 'completed'], name='nutrition_u_user_id_286d52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermeallog',
            unique_together={('user', 'meal_template', 'date')},
        ),
    ]
