# Generated by Django 5.2.8 on 2025-11-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_remove_nutritionplan_macros_nutritionplan_carbs_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='protein_g',
            field=models.FloatField(default=0),
        ),
    ]
