# Generated by Django 5.2.8 on 2025-11-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_alter_nutritionplan_protein_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='protein_g',
            field=models.PositiveIntegerField(default=150, help_text='Gramos de proteína por día'),
        ),
    ]
