# Generated by Django 5.2.8 on 2026-05-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_gym_max_athletes_gym_max_coaches_and_more'),
        ('nutrition', '0006_alter_nutritionplan_protein_g'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nutritionplan',
            index=models.Index(fields=['gym', 'status'], name='nutrition_n_gym_id_9f948b_idx'),
        ),
    ]
