# Generated by Django 5.2.8 on 2026-06-06 00:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0015_coachmessage'),
        ('nutrition', '0008_mealtemplate_deleted_at_nutritionitem_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('food_group', models.CharField(choices=[('meats', 'Carnes y derivados'), ('dairy', 'Lácteos y huevos'), ('cereals', 'Cereales y derivados'), ('legumes', 'Legumbres y derivados'), ('vegetables', 'Verduras y hortalizas'), ('fruits', 'Frutas'), ('fats', 'Grasas y aceites'), ('beverages', 'Bebidas'), ('others', 'Otros')], default='others', max_length=20)),
                ('source', models.CharField(default='CENAN', help_text='Fuente de datos nutricionales', max_length=100)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fats_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fiber_per_100g', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_foods', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, help_text='Null = alimento global (CENAN), no nulo = creado por el nutricionista del gym', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='gyms.gym')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['gym', 'food_group'], name='nutrition_f_gym_id_e58f6b_idx'), models.Index(fields=['name'], name='nutrition_f_name_caa2b0_idx')],
            },
        ),
    ]
