# Generated by Django 5.2.8 on 2026-06-06 00:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_add_food_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealFoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_g', models.DecimalField(decimal_places=1, help_text='Cantidad en gramos', max_digits=7)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fats_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_uses', to='nutrition.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='nutrition.mealtemplate')),
            ],
            options={
                'ordering': ['meal', 'order'],
            },
        ),
    ]
