# Generated by Django 5.2.8 on 2026-06-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_add_meal_food_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtemplate',
            name='weekday',
            field=models.CharField(blank=True, choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], help_text='Día de la semana (planes con estructura semanal)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mealtemplate',
            name='day_number',
            field=models.PositiveIntegerField(blank=True, help_text='Legado — usar weekday para planes nuevos', null=True),
        ),
        migrations.AlterField(
            model_name='mealtemplate',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Desayuno'), ('mid_morning', 'Media mañana'), ('lunch', 'Almuerzo'), ('afternoon_snack', 'Merienda'), ('dinner', 'Cena'), ('late_snack', 'Recena')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='mealtemplate',
            index=models.Index(fields=['plan', 'weekday', 'meal_type'], name='nutrition_m_plan_id_3e2e2d_idx'),
        ),
    ]
