# Generated by Django 5.2.8 on 2026-06-12 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0011_add_weekday_and_meal_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usermeallog',
            name='nutrition_u_user_id_286d52_idx',
        ),
        migrations.AddField(
            model_name='usermeallog',
            name='alternative_food_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usermeallog',
            name='status',
            field=models.CharField(choices=[('completed', 'Completado'), ('skipped', 'Saltado'), ('alternative', 'Comí otra cosa')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermeallog',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usermeallog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='usermeallog',
            index=models.Index(fields=['user', 'status'], name='nutrition_u_user_id_b2a1c3_idx'),
        ),
    ]
