# Generated by Django 5.2.8 on 2026-06-17 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0013_remove_usermeallog_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeallog',
            name='nutritionist_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='usermeallog',
            name='nutritionist_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usermeallog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='meal_proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='usermeallog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermeallog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_meal_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermeallog',
            name='xp_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='usermeallog',
            index=models.Index(fields=['nutritionist_approved', 'date'], name='nutrition_u_nutriti_fe985a_idx'),
        ),
    ]
