# Generated by Django 5.2.8 on 2026-06-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0014_usermeallog_photo_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernutritionplan',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('scheduled', 'Programado'), ('paused', 'Pausado'), ('completed', 'Completado')], default='active', max_length=20),
        ),
    ]
