# Generated by Django 5.2.8 on 2026-06-20 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0015_add_scheduled_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='created_for',
            field=models.ForeignKey(blank=True, help_text='Si está seteado, es un plan personal de ese atleta y no aparece en la biblioteca.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_nutrition_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
