# Generated by Django 5.2.8 on 2026-06-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0016_add_created_for_to_nutrition_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernutritionplan',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el atleta solicitó revisión de su semana al nutricionista', null=True),
        ),
    ]
