# Generated by Django 5.2.8 on 2026-06-24 21:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0018_remove_usernutritionplan_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeallog',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
