# Generated by Django 5.2.8 on 2026-06-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0019_alter_usermeallog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeallog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='meal_proofs/%Y/%m/'),
        ),
    ]
