[build]
builder = "nixpacks"

[deploy]
startCommand = "bash build.sh"
healthcheckPath = "/api/system/feature-flags/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
