# Generated by Django 5.2.8 on 2026-05-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_athletes',
            field=models.PositiveIntegerField(default=50, help_text='Máximo de atletas permitidos'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_coaches',
            field=models.PositiveIntegerField(default=2, help_text='Máximo de coaches permitidos'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_nutritionists',
            field=models.PositiveIntegerField(default=1, help_text='Máximo de nutricionistas permitidos'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('annual', 'Anual'), ('custom', 'Personalizado')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='PEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
