# Generated by Django 5.2.8 on 2026-05-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_max_athletes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['display_order', 'price']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en la interfaz'),
        ),
    ]
