# Generated by Django 5.2.8 on 2026-06-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_payment_deleted_at_subscription_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='PEN', max_length=10),
        ),
    ]
