# Generated by Django 5.2.8 on 2026-05-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_badge_gym'),
        ('gyms', '0004_gym_max_athletes_gym_max_coaches_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['gym', 'status'], name='challenges__gym_id_29d153_idx'),
        ),
    ]
