# Generated by Django 5.2.8 on 2026-06-10 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_badge_deleted_at_challenge_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='verification_type',
            field=models.CharField(choices=[('automatic', 'Automática'), ('manual', 'Manual (aprobación del responsable)')], default='automatic', help_text='Automática: el sistema calcula el progreso. Manual: el responsable aprueba.', max_length=20),
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='evidence_note',
            field=models.TextField(blank=True, help_text='Evidencia textual enviada por el atleta para retos de verificación manual.'),
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Motivo del rechazo comunicado al atleta.'),
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Coach o nutricionista que aprobó/rechazó la participación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challengeparticipation',
            name='status',
            field=models.CharField(choices=[('joined', 'Unido'), ('pending_review', 'Pendiente de revisión'), ('completed', 'Completado'), ('rejected', 'Rechazado'), ('dropped', 'Abandonado')], default='joined', max_length=20),
        ),
        migrations.AddIndex(
            model_name='challengeparticipation',
            index=models.Index(fields=['challenge', 'status'], name='challenges__challen_0027e9_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipation',
            index=models.Index(fields=['user', 'status'], name='challenges__user_id_104bf1_idx'),
        ),
    ]
