# Generated by Django 5.2.8 on 2026-06-10 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_add_verification_fields'),
        ('gyms', '0016_add_max_participants_and_target_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Límite de inscriptos. Null = sin límite.', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='target_role',
            field=models.CharField(choices=[('all', 'Todos'), ('athlete', 'Solo atletas'), ('coach', 'Solo coaches'), ('nutritionist', 'Solo nutricionistas')], default='all', help_text='Rol al que va dirigido el reto. Solo usuarios con ese rol pueden unirse.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['gym', 'status', 'target_role'], name='challenges__gym_id_fb0c39_idx'),
        ),
    ]
