# Generated by Django 5.2.8 on 2026-06-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_add_max_participants_and_target_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
