# Generated by Django 5.2.8 on 2026-06-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_remove_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeparticipation',
            name='is_winner',
            field=models.BooleanField(default=False, help_text='True si el staff declaró a este atleta ganador del reto.'),
        ),
    ]
