# Generated by Django 5.2.8 on 2026-05-15 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_gym_max_athletes_gym_max_coaches_and_more'),
        ('workouts', '0004_alter_workoutsession_gym'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workoutroutine',
            index=models.Index(fields=['gym', 'status'], name='workouts_wo_gym_id_93e608_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'status', 'performed_at'], name='workouts_wo_user_id_47ab76_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['gym', 'performed_at'], name='workouts_wo_gym_id_2ceb17_idx'),
        ),
    ]
