# Generated by Django 5.2.8 on 2026-06-23 03:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_weekly_routine_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExerciseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sets_completed', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('routine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='workouts.routineexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['routine_exercise__order'],
                'unique_together': {('session', 'routine_exercise')},
            },
        ),
    ]
