# Generated by Django 5.2.8 on 2026-06-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
