# Generated by Django 5.2.8

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_userpoints_related_challenge'),
        ('nutrition', '0004_remove_nutritionplan_macros_nutritionplan_carbs_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='related_nutrition_plan',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='points_awarded',
                to='nutrition.nutritionplan'
            ),
        ),
    ]
