# Generated by Django 5.2.8 on 2026-06-20 00:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_athletestreak'),
        ('gyms', '0021_athlete_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymPointsConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nutrition_week_points', models.PositiveIntegerField(default=100, help_text='Puntos otorgados al atleta cuando el nutricionista aprueba su semana')),
                ('workout_week_points', models.PositiveIntegerField(default=50, help_text='Puntos otorgados al atleta al completar una semana de rutinas')),
                ('challenge_points', models.PositiveIntegerField(default=200, help_text='Puntos base otorgados al completar un reto')),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_config', to='gyms.gym')),
            ],
            options={
                'verbose_name': 'Configuración de puntos',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/')),
                ('points_cost', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Null = stock ilimitado', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='gyms.gym')),
            ],
            options={
                'ordering': ['points_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Nota del admin al aprobar/rechazar')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='gamification.reward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
