# Generated by Django 5.2.8 on 2026-06-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_athletestreak_onetomany'),
        ('gyms', '0021_athlete_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletestreak',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_streaks', to='gyms.gym'),
        ),
    ]
