# Generated by Django 5.2.8 on 2026-06-23 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_athletestreak_fix_related_name'),
        ('workouts', '0009_add_session_exercise_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='pending_points',
            field=models.IntegerField(default=0, help_text='Puntos que el atleta solicita; se confirman al aprobar.'),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='related_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='workouts.workoutsession'),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
