# Generated by Django 5.2.8 on 2026-06-23 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_add_max_participants_and_target_role'),
        ('gamification', '0007_userpoints_pending_approval'),
        ('nutrition', '0018_remove_usernutritionplan_unique_together'),
        ('workouts', '0009_add_session_exercise_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='week_start',
            field=models.DateField(blank=True, db_index=True, help_text="Lunes de la semana premiada. Solo aplica a source='workout_week'.", null=True),
        ),
        migrations.AddConstraint(
            model_name='userpoints',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'workout_week')), fields=('user', 'week_start'), name='unique_workout_week_per_user'),
        ),
    ]
