# Generated by Django 5.2.8 on 2026-06-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_userpoints_week_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AthleteStreak',
        ),
    ]
