# Generated by Django 5.2.8 on 2026-07-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_alter_reward_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardredemption',
            name='pickup_info',
            field=models.TextField(blank=True, help_text='Mensaje del admin sobre cuándo/cómo recoger el producto'),
        ),
    ]
