# Generated by Django 5.2.8 on 2026-04-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gym_contact_email_gym_website_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/logos/'),
        ),
        migrations.AddField(
            model_name='gym',
            name='ruc',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
