# Generated by Django 5.2.8 on 2026-05-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_gym_logo_gym_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='max_athletes',
            field=models.IntegerField(default=100, help_text='Límite de atletas activos'),
        ),
        migrations.AddField(
            model_name='gym',
            name='max_coaches',
            field=models.IntegerField(default=2, help_text='Límite de coaches activos'),
        ),
        migrations.AddField(
            model_name='gym',
            name='max_nutritionists',
            field=models.IntegerField(default=2, help_text='Límite de nutricionistas activos'),
        ),
    ]
