# Generated by Django 5.2.8 on 2026-05-23 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('gyms', '0005_gymmembershipplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymFeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_flags', to='core.featureflag')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='gyms.gym')),
            ],
            options={
                'ordering': ['feature_flag__name'],
                'unique_together': {('gym', 'feature_flag')},
            },
        ),
    ]
