# Generated by Django 5.2.8 on 2026-05-29 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_gymfeatureflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('qr', 'QR Code'), ('self', 'Autoregistro')], default='manual', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='gyms.branch')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='gyms.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['gym', 'timestamp'], name='gyms_checki_gym_id_04bef1_idx'), models.Index(fields=['user', 'timestamp'], name='gyms_checki_user_id_7a49e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoachAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_assignments', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to='gyms.gym')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('coach', 'athlete')},
            },
        ),
    ]
