# Generated by Django 5.2.8 on 2026-06-01 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_nutritionistassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('routine_assigned', 'Rutina Asignada'), ('routine_updated', 'Rutina Actualizada'), ('plan_assigned', 'Plan Nutricional Asignado'), ('plan_updated', 'Plan Nutricional Actualizado'), ('challenge_completed', 'Reto Completado'), ('badge_earned', 'Medalla Obtenida'), ('checkin_reminder', 'Recordatorio de Check-in'), ('message', 'Mensaje'), ('system', 'Sistema')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_notifications', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gyms.gym')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='gyms_notifi_recipie_231041_idx'), models.Index(fields=['recipient', '-created_at'], name='gyms_notifi_recipie_9352a0_idx')],
            },
        ),
    ]
