# Generated by Django 5.2.8 on 2026-06-02 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0011_gymsubscription_gympayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionistAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('appointment_type', models.CharField(choices=[('first', 'Primera Consulta'), ('followup', 'Consulta de Seguimiento')], default='followup', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No Asistió')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_appointments', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_appointments', to='gyms.gym')),
                ('nutritionist', models.ForeignKey(limit_choices_to={'role': 'nutritionist'}, on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['nutritionist', 'scheduled_at'], name='gyms_nutrit_nutriti_218940_idx'), models.Index(fields=['athlete', 'scheduled_at'], name='gyms_nutrit_athlete_b2b5ac_idx'), models.Index(fields=['gym', 'status'], name='gyms_nutrit_gym_id_bd6d10_idx')],
            },
        ),
        migrations.CreateModel(
            name='NutritionistMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sender_is_nutritionist', models.BooleanField(default=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_nutri_messages', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutri_messages', to='gyms.gym')),
                ('nutritionist', models.ForeignKey(limit_choices_to={'role': 'nutritionist'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_nutri_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nutritionist', 'athlete', '-created_at'], name='gyms_nutrit_nutriti_afc128_idx')],
            },
        ),
    ]
