# Generated by Django 5.2.8 on 2026-06-03 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0014_gymmembershipplan_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sender_is_coach', models.BooleanField(default=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_coach_messages', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_coach_messages', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_messages', to='gyms.gym')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coach', 'athlete', '-created_at'], name='gyms_coachm_coach_i_763adf_idx')],
            },
        ),
    ]
