# Generated by Django 5.2.8 on 2026-06-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0015_coachmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('routine_assigned', 'Rutina Asignada'), ('routine_updated', 'Rutina Actualizada'), ('plan_assigned', 'Plan Nutricional Asignado'), ('plan_updated', 'Plan Nutricional Actualizado'), ('challenge_completed', 'Reto Completado'), ('challenge_pending_review', 'Reto Pendiente de Revisión'), ('challenge_rejected', 'Reto Rechazado'), ('badge_earned', 'Medalla Obtenida'), ('checkin_reminder', 'Recordatorio de Check-in'), ('message', 'Mensaje'), ('system', 'Sistema')], max_length=30),
        ),
    ]
