# Generated by Django 5.2.8 on 2026-06-16 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0017_nutritionist_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('routine_assigned', 'Rutina Asignada'), ('routine_updated', 'Rutina Actualizada'), ('plan_assigned', 'Plan Nutricional Asignado'), ('plan_updated', 'Plan Nutricional Actualizado'), ('challenge_completed', 'Reto Completado'), ('challenge_pending_review', 'Reto Pendiente de Revisión'), ('challenge_rejected', 'Reto Rechazado'), ('badge_earned', 'Medalla Obtenida'), ('checkin_reminder', 'Recordatorio de Check-in'), ('message', 'Mensaje'), ('appointment_scheduled', 'Cita Agendada'), ('appointment_cancelled', 'Cita Cancelada'), ('system', 'Sistema')], max_length=30),
        ),
        migrations.CreateModel(
            name='AvailabilityOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_overrides', to='gyms.gym')),
                ('nutritionist', models.ForeignKey(limit_choices_to={'role': 'nutritionist'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excepción de disponibilidad',
                'verbose_name_plural': 'Excepciones de disponibilidad',
                'ordering': ['date'],
                'unique_together': {('nutritionist', 'gym', 'date')},
            },
        ),
    ]
