# Generated by Django 5.2.8 on 2026-06-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0018_availability_override_and_appointment_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionistappointment',
            name='cancelled_by',
            field=models.CharField(blank=True, help_text='athlete o nutritionist', max_length=20),
        ),
        migrations.AddField(
            model_name='nutritionistappointment',
            name='reschedule_note',
            field=models.TextField(blank=True, help_text='Nota del atleta al solicitar reprogramación'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('routine_assigned', 'Rutina Asignada'), ('routine_updated', 'Rutina Actualizada'), ('plan_assigned', 'Plan Nutricional Asignado'), ('plan_updated', 'Plan Nutricional Actualizado'), ('challenge_completed', 'Reto Completado'), ('challenge_pending_review', 'Reto Pendiente de Revisión'), ('challenge_rejected', 'Reto Rechazado'), ('badge_earned', 'Medalla Obtenida'), ('checkin_reminder', 'Recordatorio de Check-in'), ('message', 'Mensaje'), ('appointment_scheduled', 'Cita Agendada'), ('appointment_confirmed', 'Cita Confirmada'), ('appointment_cancelled', 'Cita Cancelada'), ('appointment_reschedule_requested', 'Reprogramación Solicitada'), ('appointment_rescheduled', 'Cita Reprogramada'), ('system', 'Sistema')], max_length=40),
        ),
        migrations.AlterField(
            model_name='nutritionistappointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No Asistió'), ('reschedule_requested', 'Reprogramación Solicitada')], default='scheduled', max_length=30),
        ),
    ]
