# Generated by Django 5.2.8 on 2026-06-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0019_appointment_confirm_reschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionistappointment',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Notas clínicas privadas del nutricionista: anamnesis, diagnóstico, plan de acción'),
        ),
    ]
