# Generated by Django 5.2.8 on 2026-06-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0023_gymsubscription_crm_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/logos/'),
        ),
    ]
