# Generated by Django 5.2.8 on 2026-06-29 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_deleted_at_featureflag_deleted_at_and_more'),
        ('gyms', '0024_announcement_gym_and_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalannouncement',
            name='target_gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='gyms.gym', verbose_name='Gimnasio destino'),
        ),
        migrations.AlterField(
            model_name='globalannouncement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Todos los usuarios'), ('gym_admins', 'Administradores'), ('athletes', 'Atletas'), ('coaches', 'Coaches'), ('nutritionists', 'Nutricionistas'), ('receptionists', 'Atención al Cliente')], default='all', max_length=20),
        ),
    ]
